### ISSUE TITLE
Errors on xiaomi device

### ISSUE THREAD

**Issue by ItsKlork** [judemanutd/AutoStarter#23]
`W/System.err: com.judemanutd.autostarter.AutoStartPermissionHelper.startIntent(AutoStartPermissionHelper.kt:268)`

I get 5 more errors when doing `AutoStartPermissionHelper.getInstance().getAutoStartPermission(getApplicationContext());`

get this on a xiaomi device. help?

**Comment by judemanutd** [comment]
Could you post the entire error log please

**Comment by ItsKlork** [comment]
im trying this on the xiaomi redmi note 7

**Comment by judemanutd** [comment]
@ItsKlork  Just tried it out on the redmi note 7 and works fine. Could you post the error log along with the android version and miui version on the phone. 

Have you run the example app from the repo, does that work?

**Comment by ItsKlork** [comment]
2019-12-07 11:28:04.696 21706-21706/com.dev.mapup W/System.err:     at com.judemanutd.autostarter.AutoStartPermissionHelper.startIntent(AutoStartPermissionHelper.kt:268)
2019-12-07 11:28:04.696 21706-21706/com.dev.mapup W/System.err:     at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStartXiaomi(AutoStartPermissionHelper.kt:122)
2019-12-07 11:28:04.697 21706-21706/com.dev.mapup W/System.err:     at com.judemanutd.autostarter.AutoStartPermissionHelper.getAutoStartPermission(AutoStartPermissionHelper.kt:85)
2019-12-07 11:28:04.697 21706-21706/com.dev.mapup W/System.err:     at com.judemanutd.autostarter.AutoStartPermissionHelper.startIntent(AutoStartPermissionHelper.kt:268)
2019-12-07 11:28:04.697 21706-21706/com.dev.mapup W/System.err:     at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStartXiaomi(AutoStartPermissionHelper.kt:122)
2019-12-07 11:28:04.697 21706-21706/com.dev.mapup W/System.err:     at com.judemanutd.autostarter.AutoStartPermissionHelper.getAutoStartPermission(AutoStartPermissionHelper.kt:85)

**Comment by ItsKlork** [comment]
nothing is happening

**Comment by judemanutd** [comment]
@ItsKlork  Which miui version are you on?

**Comment by ItsKlork** [comment]
MIUI Global 11.0.4

**Comment by judemanutd** [comment]
Got the same phone with the same version, works perfectly fine, no clue what's up.

**Comment by judemanutd** [comment]
If you could create a separate repo recreating this exact bug I could give this a try else looks like there's something local to your phone that's causing the issue

**Comment by ItsKlork** [comment]
How should I use the AutoStarter in code (in onCreate)? Just to be sure

**Comment by judemanutd** [comment]
Yep that should work fine, it doesn't really depend on any activity lifecycle as such but any lifecycle events after onCreate should be more than safe to use the code in, instead of using the application context try using the activity context instead and see if that works

**Comment by judemanutd** [comment]
closing this issue as there is no further action to be taken
