### ISSUE TITLE
[Feature Request] Add support for OnePlus devices

### ISSUE THREAD

**Issue by karlmarxlopez** [judemanutd/AutoStarter#34]
Hi, is it possible to support OnePlus devices? [AppKillManager has an implementation for this](https://github.com/thelittlefireman/AppKillerManager/blob/master/appkillermanager/src/main/java/com/thelittlefireman/appkillermanager/devices/OnePlus.java)

**Comment by judemanutd** [comment]
Hey @karlmarxlopez, I can surely include that although I cannot really verify if it is still applicable. OEM's often change their package names. Can you verify that it currently works using that library?

**Comment by karlmarxlopez** [comment]
Hi, thank you! I don't have access to a OnePlus device as of the moment. Can you publish it as beta so that we can test it when we have a device?

**Comment by judemanutd** [comment]
Sure, that seems do-able. I'll get that sorted soon.

**Comment by judemanutd** [comment]
@karlmarxlopez pushed up a new updated to the library v1.0.8. Give it a try and let me know if it works.

**Comment by riyaistar** [comment]
I have a device of one plus 6 with oxygen version and i am getting the below exception 


2020-05-09 02:58:32.676 3670-3670/? W/System.err: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.oneplus.security/com.oneplus.security.chainlaunch.view.ChainLaunchAppListActivity}; have you declared this activity in your AndroidManifest.xml?
2020-05-09 02:58:32.676 3670-3670/? W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2239)
2020-05-09 02:58:32.676 3670-3670/? W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1895)
2020-05-09 02:58:32.676 3670-3670/? W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:5205)
2020-05-09 02:58:32.676 3670-3670/? W/System.err:     at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
2020-05-09 02:58:32.676 3670-3670/? W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:5163)
2020-05-09 02:58:32.676 3670-3670/? W/System.err:     at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
2020-05-09 02:58:32.676 3670-3670/? W/System.err:     at android.app.Activity.startActivity(Activity.java:5534)
2020-05-09 02:58:32.676 3670-3670/? W/System.err:     at android.app.Activity.startActivity(Activity.java:5502)
2020-05-09 02:58:32.676 3670-3670/? W/System.err:     at com.judemanutd.autostarter.AutoStartPermissionHelper.startIntent(AutoStartPermissionHelper.kt:325)
2020-05-09 02:58:32.676 3670-3670/? W/System.err:     at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStartOnePlus(AutoStartPermissionHelper.kt:308)
2020-05-09 02:58:32.676 3670-3670/? W/System.err:     at com.judemanutd.autostarter.AutoStartPermissionHelper.getAutoStartPermission(AutoStartPermissionHelper.kt:118)

**Comment by Xxshark888xX** [comment]
> I have a device of one plus 6 with oxygen version and i am getting the below exception
> 
> 2020-05-09 02:58:32.676 3670-3670/? W/System.err: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.oneplus.security/com.oneplus.security.chainlaunch.view.ChainLaunchAppListActivity}; have you declared this activity in your AndroidManifest.xml?
> 2020-05-09 02:58:32.676 3670-3670/? W/System.err: at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2239)
> 2020-05-09 02:58:32.676 3670-3670/? W/System.err: at android.app.Instrumentation.execStartActivity(Instrumentation.java:1895)
> 2020-05-09 02:58:32.676 3670-3670/? W/System.err: at android.app.Activity.startActivityForResult(Activity.java:5205)
> 2020-05-09 02:58:32.676 3670-3670/? W/System.err: at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
> 2020-05-09 02:58:32.676 3670-3670/? W/System.err: at android.app.Activity.startActivityForResult(Activity.java:5163)
> 2020-05-09 02:58:32.676 3670-3670/? W/System.err: at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
> 2020-05-09 02:58:32.676 3670-3670/? W/System.err: at android.app.Activity.startActivity(Activity.java:5534)
> 2020-05-09 02:58:32.676 3670-3670/? W/System.err: at android.app.Activity.startActivity(Activity.java:5502)
> 2020-05-09 02:58:32.676 3670-3670/? W/System.err: at com.judemanutd.autostarter.AutoStartPermissionHelper.startIntent(AutoStartPermissionHelper.kt:325)
> 2020-05-09 02:58:32.676 3670-3670/? W/System.err: at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStartOnePlus(AutoStartPermissionHelper.kt:308)
> 2020-05-09 02:58:32.676 3670-3670/? W/System.err: at com.judemanutd.autostarter.AutoStartPermissionHelper.getAutoStartPermission(AutoStartPermissionHelper.kt:118)

If you still have access to that device, you should use adb in order to find the correct intent. 

Check the https://github.com/judemanutd/AutoStarter/issues/47#issuecomment-651002811
