### ISSUE TITLE
SecurityException on Huawei HUAWEI nova 5T Android 10

### ISSUE THREAD

**Issue by mravki** [judemanutd/AutoStarter#76]
Hi, I got a Crash on Huawei HUAWEI nova 5T Android 10 (SDK 29): 
`java.lang.SecurityException: 
  at android.os.Parcel.createException (Parcel.java:2071)
  at android.os.Parcel.readException (Parcel.java:2039)
  at android.os.Parcel.readException (Parcel.java:1987)
  at android.app.IActivityTaskManager$Stub$Proxy.startActivity (IActivityTaskManager.java:3888)
  at android.app.Instrumentation.execStartActivity (Instrumentation.java:1738)
  at android.app.Activity.startActivityForResult (Activity.java:5368)
  at androidx.activity.ComponentActivity.startActivityForResult (ComponentActivity.java:597)
  at android.app.Activity.startActivityForResult (Activity.java:5304)
  at androidx.activity.ComponentActivity.startActivityForResult (ComponentActivity.java:583)
  at android.app.Activity.startActivity (Activity.java:5751)
  at android.app.Activity.startActivity (Activity.java:5719)
  at com.judemanutd.autostarter.AutoStartPermissionHelper.startIntent (AutoStartPermissionHelper.kt:333)
  at com.judemanutd.autostarter.AutoStartPermissionHelper.openAutoStartScreen (AutoStartPermissionHelper.kt:428)
  at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStart (AutoStartPermissionHelper.kt:452)
  at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStartHuawei (AutoStartPermissionHelper.kt:239)
  at com.judemanutd.autostarter.AutoStartPermissionHelper.getAutoStartPermission (AutoStartPermissionHelper.kt:157)`
   The code that caused this is in Java:
`AutoStartPermissionHelper.Companion.getInstance().getAutoStartPermission(getContext(), true, true);`
Let me know if you need more information about it.

**Comment by kitfist0** [comment]
Huawei Nova 7i (JNY-LX2), Android 10

```
Fatal Exception: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.huawei.systemmanager/.startupmgr.ui.StartupNormalAppListActivity } from ProcessRecord{c5d7acb 20475:com.myapp/u0a525} (pid=20475, uid=10525) requires com.huawei.permission.external_app_settings.USE_COMPONENT
       at android.os.Parcel.createException(Parcel.java:2090)
       at android.os.Parcel.readException(Parcel.java:2058)
       at android.os.Parcel.readException(Parcel.java:2006)
       at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3908)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1738)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1049)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1005)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.startIntent(AutoStartPermissionHelper.kt:333)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.openAutoStartScreen(AutoStartPermissionHelper.kt:428)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStart(AutoStartPermissionHelper.kt:452)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStartHuawei(AutoStartPermissionHelper.kt:239)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.getAutoStartPermission(AutoStartPermissionHelper.kt:157)
```

**Comment by kitfist0** [comment]
Huawei P30, Android 10

```
Fatal Exception: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.huawei.systemmanager/.startupmgr.ui.StartupNormalAppListActivity } from ProcessRecord{caee0c3 5228:com.myapp/u0a715} (pid=5228, uid=10715) requires com.huawei.permission.external_app_settings.USE_COMPONENT
       at android.os.Parcel.createException(Parcel.java:2090)
       at android.os.Parcel.readException(Parcel.java:2058)
       at android.os.Parcel.readException(Parcel.java:2006)
       at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3908)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1738)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1049)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1005)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.startIntent(AutoStartPermissionHelper.kt:333)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.openAutoStartScreen(AutoStartPermissionHelper.kt:428)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStart(AutoStartPermissionHelper.kt:452)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStartHuawei(AutoStartPermissionHelper.kt:239)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.getAutoStartPermission(AutoStartPermissionHelper.kt:157)
```

**Comment by kitfist0** [comment]
Huawei P30 Pro, Android 10

```
Fatal Exception: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.huawei.systemmanager/.startupmgr.ui.StartupNormalAppListActivity } from ProcessRecord{91c9867 8979:com.myapp/u0a353} (pid=8979, uid=10353) requires com.huawei.permission.external_app_settings.USE_COMPONENT
       at android.os.Parcel.createException(Parcel.java:2090)
       at android.os.Parcel.readException(Parcel.java:2058)
       at android.os.Parcel.readException(Parcel.java:2006)
       at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3908)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1738)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1049)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1005)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.startIntent(AutoStartPermissionHelper.kt:333)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.openAutoStartScreen(AutoStartPermissionHelper.kt:428)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStart(AutoStartPermissionHelper.kt:452)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStartHuawei(AutoStartPermissionHelper.kt:239)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.getAutoStartPermission(AutoStartPermissionHelper.kt:157)
```

**Comment by evgenii-komornyi** [comment]
Huawei P30 Lite and Pro
![image](https://github.com/judemanutd/AutoStarter/assets/12217834/adb57427-52b5-4d64-b73e-891f6caa0bce)
