### ISSUE TITLE
SecurityException: Permission Denial

### ISSUE THREAD

**Issue by kitfist0** [judemanutd/AutoStarter#84]
The code:
```
AutoStartPermissionHelper.getInstance().getAutoStartPermission(context, true, true)
```
**Stack trace:**
```
Fatal Exception: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.huawei.systemmanager/.startupmgr.ui.StartupNormalAppListActivity } from ProcessRecord{c5d7acb 20475:com.myapp/u0a525} (pid=20475, uid=10525) requires com.huawei.permission.external_app_settings.USE_COMPONENT
       at android.os.Parcel.createException(Parcel.java:2090)
       at android.os.Parcel.readException(Parcel.java:2058)
       at android.os.Parcel.readException(Parcel.java:2006)
       at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3908)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1738)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1049)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1005)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.startIntent(AutoStartPermissionHelper.kt:333)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.openAutoStartScreen(AutoStartPermissionHelper.kt:428)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStart(AutoStartPermissionHelper.kt:452)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStartHuawei(AutoStartPermissionHelper.kt:239)
       at com.judemanutd.autostarter.AutoStartPermissionHelper.getAutoStartPermission(AutoStartPermissionHelper.kt:157)
```
**List of devices on which this happened:**

Huawei
- Nova 7 SE  (CDY-NX9B), Android 10
- Nova 7i (JNY-LX2), Android 10
- Nova 5i Pro (SPN-AL00), Android 10
- Nova 5T, Android 10
- Mate 30 Pro (LIO-L29), Android 10
- Mate 20 Pro, Android 10
- Mate 20 X (5G), Android 10
- P30, Android 10
- P30 Pro, Android 10
- Nova 9 (NAM-LX9), Android 11

Asus
- ZenFone Selfie (ZD551KL), Android 6.0.1
- ZenFone Max Plus M1 (ZB570TL), Android 7.0
- ZenFone Max Plus M1 (ZB570TL), Android 10

Oppo
- F1S (A1601), Android 6.0
- F3 (CPH1609), Android 6.0

**Comment by AR0011** [comment]
> The code:
> ```
> AutoStartPermissionHelper.getInstance().getAutoStartPermission(context, true, true)
> ```
> **Stack trace:**
> ```
> Fatal Exception: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.huawei.systemmanager/.startupmgr.ui.StartupNormalAppListActivity } from ProcessRecord{c5d7acb 20475:com.myapp/u0a525} (pid=20475, uid=10525) requires com.huawei.permission.external_app_settings.USE_COMPONENT
>        at android.os.Parcel.createException(Parcel.java:2090)
>        at android.os.Parcel.readException(Parcel.java:2058)
>        at android.os.Parcel.readException(Parcel.java:2006)
>        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3908)
>        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1738)
>        at android.app.ContextImpl.startActivity(ContextImpl.java:1049)
>        at android.app.ContextImpl.startActivity(ContextImpl.java:1005)
>        at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
>        at com.judemanutd.autostarter.AutoStartPermissionHelper.startIntent(AutoStartPermissionHelper.kt:333)
>        at com.judemanutd.autostarter.AutoStartPermissionHelper.openAutoStartScreen(AutoStartPermissionHelper.kt:428)
>        at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStart(AutoStartPermissionHelper.kt:452)
>        at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStartHuawei(AutoStartPermissionHelper.kt:239)
>        at com.judemanutd.autostarter.AutoStartPermissionHelper.getAutoStartPermission(AutoStartPermissionHelper.kt:157)
> ```
> **List of devices on which this happened:**
> 
> Huawei
> - Nova 7 SE  (CDY-NX9B), Android 10
> - Nova 7i (JNY-LX2), Android 10
> - Nova 5i Pro (SPN-AL00), Android 10
# > > - Nova 5T, An[]- [ ] ()_~~~~_droid 10
> - Mate 30 Pro (LIO-L29), Android 10
> - Mate 20 Pro, Android 10
> - Mate 20 X (5G), Android 10
> - P30, Android 10
> - P30 Pro, Android 10
> - Nova 9 (NAM-LX9), Android 11
> 
> Asus
> - ZenFone Selfie (ZD551KL), Android 6.0.1
> - ZenFone Max Plus M1 (ZB570TL), Android 7.0
> - ZenFone Max Plus M1 (ZB570TL), Android 10
> 
> Oppo
> - F1S (A1601), Android 6.0
> - F3 (CPH1609), Android 6.0

> @

**Comment by HorizonItApps** [comment]
@kitfist0 Did you find a solution? I am facing the same issue.

**Comment by kitfist0** [comment]
> @kitfist0 Did you find a solution? I am facing the same issue.

Unfortunately no

**Comment by AleksArm** [comment]
Guys Any update for this issue?

**Comment by nizam-betterapp** [comment]
I am facing this issue as well. Any solutions please?

**Comment by MiraBery** [comment]
> The code:
> ```
> AutoStartPermissionHelper.getInstance().getAutoStartPermission(context, true, true)
> ```
> **Stack trace:**
> ```
> Fatal Exception: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.huawei.systemmanager/.startupmgr.ui.StartupNormalAppListActivity } from ProcessRecord{c5d7acb 20475:com.myapp/u0a525} (pid=20475, uid=10525) requires com.huawei.permission.external_app_settings.USE_COMPONENT
>        at android.os.Parcel.createException(Parcel.java:2090)
>        at android.os.Parcel.readException(Parcel.java:2058)
>        at android.os.Parcel.readException(Parcel.java:2006)
>        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3908)
>        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1738)
>        at android.app.ContextImpl.startActivity(ContextImpl.java:1049)
>        at android.app.ContextImpl.startActivity(ContextImpl.java:1005)
>        at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
>        at com.judemanutd.autostarter.AutoStartPermissionHelper.startIntent(AutoStartPermissionHelper.kt:333)
>        at com.judemanutd.autostarter.AutoStartPermissionHelper.openAutoStartScreen(AutoStartPermissionHelper.kt:428)
>        at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStart(AutoStartPermissionHelper.kt:452)
>        at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStartHuawei(AutoStartPermissionHelper.kt:239)
>        at com.judemanutd.autostarter.AutoStartPermissionHelper.getAutoStartPermission(AutoStartPermissionHelper.kt:157)
> ```
> **List of devices on which this happened:**
> 
> Huawei
> - Nova 7 SE  (CDY-NX9B), Android 10
> - Nova 7i (JNY-LX2), Android 10
> - Nova 5i Pro (SPN-AL00), Android 10
> - Nova 5T, Android 10
> - Mate 30 Pro (LIO-L29), Android 10
> - Mate 20 Pro, Android 10
> - Mate 20 X (5G), Android 10
> - P30, Android 10
> - P30 Pro, Android 10
> - Nova 9 (NAM-LX9), Android 11
> 
> Asus
> - ZenFone Selfie (ZD551KL), Android 6.0.1
> - ZenFone Max Plus M1 (ZB570TL), Android 7.0
> - ZenFone Max Plus M1 (ZB570TL), Android 10
> 
> Oppo
> - F1S (A1601), Android 6.0
> - F3 (CPH1609), Android 6.0
